[package]
name = "store-copy"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.13"

[build-dependencies]
winres = "0.1"
